'use strict';
const {days:DAYS,camps:CAMP_LIST,points:P}=window.TRIP;
const CAMPS=Object.fromEntries(CAMP_LIST.map(c=>[c.id,c]));
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>new Date(d.date+'T12:00:00').toLocaleDateString('ar-SA-u-ca-gregory',{weekday:'long',day:'numeric',month:'long'});
const money=c=>`${c.price[0]===c.price[1]?c.price[0]:c.price.join('–')} ${c.currency}`;
const search=name=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(name);
const maps=k=>search(P[k].name);
const link=(href,label)=>`<a href="${esc(href)}" target="_blank" rel="noopener">${label}</a>`;
const direction=(keys,mode='driving')=>{const q=k=>(CAMPS[k]||k==='depot')?P[k].name:P[k].xy.join(',');return 'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(q(keys[0]))+'&destination='+encodeURIComponent(q(keys.at(-1)))+'&travelmode='+mode+(keys.length>2?'&waypoints='+encodeURIComponent(keys.slice(1,-1).map(q).join('|')):'')};
let selected=null,currentDay=0,galleryIndex=0,lastFocus;
function photos(d){const c=CAMPS[d.camp];const arr=c&&c.image?[{u:c.image,c:c.name,src:c.imageSource}]:[];if(d.imageKey&&typeof IMG!=='undefined'&&IMG[d.imageKey]&&![1,2,11].includes(d.n))arr.push({u:IMG[d.imageKey],c:'مناظر الوجهة · '+d.title,src:maps(d.stops.find(k=>!CAMPS[k])||d.stops[0])});if(!arr.length&&typeof IMG!=='undefined')arr.push({u:IMG.stockholm,c:'ستوكهولم · صورة من الخطة السابقة',src:search('Stockholm')});return arr}
function campHTML(c,compact=false){return `${!compact?`<img class="camp-photo" src="${esc(c.image)}" alt="${esc(c.name)} — صورة المخيم" loading="lazy"><div class="camp-content">`:''}<span class="rating-badge" dir="ltr">★ ${c.rating.toFixed(1)} / 5</span> <span class="camp-meta">Google ${c.count?'· '+c.count.toLocaleString('en')+' مراجعة':''}</span><h3 dir="auto">${esc(c.name)}</h3><p>${esc(c.view)}</p><p class="camp-meta">${esc(c.services)}</p><p><b dir="ltr">${money(c)}</b> <span class="camp-meta">/ ليلة للكرفان والثلاثة · ${c.id==='geiranger'?'تعرفة منشورة دون الدش':'تقدير، أكد السعر النهائي'}</span></p><p class="camp-meta">${esc(c.season)}</p>${c.tradeoff?`<p class="warning">${esc(c.tradeoff)}</p>`:''}<div class="camp-links">${link(c.web,'الموقع والحجز')}${c.priceSource?link(c.priceSource,'السعر المنشور'):''}${link(search(c.name),'Google Maps')}${link(c.ratingSource,'مصدر التقييم')}${link(c.seasonSource,'الموسم والخدمات')}</div>${!compact?`<div class="photo-credit">${link(c.imageSource,'مصدر الصورة')} · روجعت معلومات المخيم 5 سبتمبر 2026</div></div>`:''}`}
$('cards').innerHTML=DAYS.map((d,i)=>{const c=CAMPS[d.camp],im=photos(d)[0];return `<article class="day-card"><button data-day="${i}" aria-label="تفاصيل اليوم ${d.n}: ${esc(d.title)}"><div class="photo"><img src="${esc(im.u)}" alt="${esc(im.c)}" loading="lazy"><span class="day-no">${d.n} · ${date(d)}</span><span class="stay-pill">${esc(d.phase)}</span></div><div class="card-body"><h3>${esc(d.title)}</h3><p class="meta">${c?esc(c.name):'تسليم الكرفان · لا مبيت'}</p><div class="card-hours"><span dir="ltr">${d.hours}</span><span>${d.km} كم تقريبًا</span></div><p class="meta">القيادة: ${d.drive}</p><div class="details">الجدول، الأسعار، الصور والمسار ←</div></div></button></article>`}).join('');
$('campCards').innerHTML=CAMP_LIST.map(c=>`<article class="camp-card"><div class="camp-night">ليلة ${date(DAYS.find(d=>d.camp===c.id))}</div>${campHTML(c)}</article>`).join('');
$('sourceList').innerHTML=TRIP.sources.map(([n,u])=>`<li>${link(u,esc(n))}</li>`).join('');
const campSum=currency=>CAMP_LIST.filter(c=>c.currency===currency).reduce((a,c)=>a.map((v,i)=>v+c.price[i]),[0,0]);
$('campTotals').innerHTML=['NOK','SEK'].map(c=>`<p><b style="font-size:24px" dir="ltr">${campSum(c).join('–')} ${c}</b></p>`).join('');
const totalKm=DAYS.reduce((s,d)=>s+d.km,0);$('distanceTotal').textContent=`نحو ${totalKm.toLocaleString('en')} كم`;$('fuelLitres').textContent=`${Math.round(totalKm*.11)}–${Math.round(totalKm*.14)}`;
function routeLinks(d){return d.segments.flatMap(s=>{if(s.mode==='road'||s.mode==='bus'){let r=[];for(let i=0;i<s.points.length-1;i+=4){const p=s.points.slice(i,i+5);r.push(link(direction(p),`${esc(P[p[0]].name)} ← ${esc(P[p.at(-1)].name)}`))}return r}if(['walk','transit'].includes(s.mode))return [link(direction([s.points[0],s.points.at(-1)],s.mode==='walk'?'walking':'transit'),s.mode==='walk'?'مسار المشي':'خيارات النقل العام')];return [link(maps(s.points[0]),s.mode==='ferry'?'مرفأ العبّارة':s.mode==='train'?'محطة القطار':'رصيف القارب')] }).join('')}
function openDay(i){lastFocus=document.activeElement;currentDay=i;galleryIndex=0;renderModal();$('dayDialog').showModal();document.body.classList.add('modal-open')}
function closeModal(){$('dayDialog').close()}
function renderModal(){const d=DAYS[currentDay],c=CAMPS[d.camp],g=photos(d),im=g[galleryIndex];$('modal').innerHTML=`<div class="modal-toolbar"><button id="closeDialog" aria-label="إغلاق التفاصيل">✕ إغلاق</button><button id="prevDay" ${currentDay===0?'disabled':''}>اليوم السابق</button><button id="nextDay" ${currentDay===10?'disabled':''}>اليوم التالي</button></div><div class="gallery"><img id="galleryImage" src="${esc(im.u)}" alt="${esc(im.c)}"><div class="gallery-cap"><span id="galleryCaption">${esc(im.c)} · ${link(im.src,'المصدر')} · ${galleryIndex+1}/${g.length}</span></div>${g.length>1?'<button class="arrow prev" id="prevPhoto" aria-label="الصورة السابقة">‹</button><button class="arrow next" id="nextPhoto" aria-label="الصورة التالية">›</button>':''}</div><div class="modal-body"><span class="date">اليوم ${d.n} · ${date(d)} · ${esc(d.phase)}</span><h2 id="modalTitle" class="modal-title">${esc(d.title)}</h2><p class="meta"><b dir="ltr">${d.hours}</b> · نحو ${d.km} كم · قيادة ${d.drive}</p><p class="modal-desc">${esc(d.desc)}</p><ol class="schedule">${d.schedule.map(s=>`<li><time>${s.time}</time><p>${esc(s.text)}</p></li>`).join('')}</ol>${c?`<div class="info-box"><h4>مخيم الليلة</h4>${campHTML(c,true)}</div>`:''}<div class="info-box"><h4>الأنشطة والأسعار</h4><ul>${d.costs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="camp-meta">المبالغ تقديرية إلا إذا ذُكر أنها تعرفة منشورة؛ مصادر الأنشطة وروابط الحجز أدناه.</p><div class="camp-links">${activityLinks(d)}</div></div><div class="info-box"><h4>الأماكن على الخريطة</h4><div class="camp-links">${d.stops.map(k=>link(maps(k),esc(P[k].name))).join('')}</div><button id="mapDay" class="btn dark">اعرض اليوم على الخريطة</button><div class="route-links">${routeLinks(d)}</div><p class="camp-meta">قُسمت الطرق الطويلة إلى روابط قصيرة تناسب الهاتف؛ افتح الأجزاء بالترتيب. التوجيه لا يتحقق من طول الكرفان أو ارتفاعه.</p></div><div class="info-box"><h4>ما يجب الانتباه له</h4><ul>${d.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></div></div>`;
$('closeDialog').onclick=closeModal;$('prevDay').onclick=()=>changeDay(-1);$('nextDay').onclick=()=>changeDay(1);$('mapDay').onclick=()=>{closeModal();selectDay(currentDay);$('map-section').scrollIntoView({behavior:'smooth'})};if(g.length>1){$('prevPhoto').onclick=()=>moveGallery(-1);$('nextPhoto').onclick=()=>moveGallery(1)} }
function activityLinks(d){const ids={3:[4],4:[2,5],5:[6],6:[0,1],8:[7],11:[8,9]}[d.n]||[7];return ids.map(i=>link(TRIP.sources[i][1],esc(TRIP.sources[i][0]))).join('')}
function moveGallery(n){galleryIndex=(galleryIndex+n+photos(DAYS[currentDay]).length)%photos(DAYS[currentDay]).length;const g=photos(DAYS[currentDay]),im=g[galleryIndex];$('galleryImage').src=im.u;$('galleryImage').alt=im.c;$('galleryCaption').innerHTML=`${esc(im.c)} · ${link(im.src,'المصدر')} · ${galleryIndex+1}/${g.length}`}
function changeDay(delta){const next=currentDay+delta;if(next<0||next>=DAYS.length)return;currentDay=next;galleryIndex=0;renderModal();$('dayDialog').scrollTop=0;$('closeDialog').focus()}
$('cards').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b)openDay(Number(b.dataset.day))});
$('dayDialog').addEventListener('close',()=>{document.body.classList.remove('modal-open');lastFocus?.focus()});
$('dayDialog').addEventListener('click',e=>{if(e.target===$('dayDialog')){const r=$('dayDialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
document.addEventListener('keydown',e=>{if($('dayDialog').open&&['ArrowLeft','ArrowRight'].includes(e.key)){moveGallery(e.key==='ArrowLeft'?1:-1);e.preventDefault()}});
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.classList.add('image-error');e.target.alt='تعذر تحميل الصورة — افتح رابط مصدرها أو صور Google Maps';e.target.removeAttribute('src')}},true);
$('routeSelect').innerHTML='<option value="all">المسار الكامل · 19–29 سبتمبر</option>'+DAYS.map((d,i)=>`<option value="${i}">${d.n} · ${date(d)} — ${esc(d.title)}</option>`).join('');
let map,layers;const colors={road:'#216f61',ferry:'#078bb0',boat:'#078bb0',bus:'#8763a8',train:'#8763a8',walk:'#b96835',transit:'#8763a8'};
if(window.L){map=L.map('map',{scrollWheelZoom:false}).setView([61,11],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);layers=L.layerGroup().addTo(map)}else{$('map').innerHTML='<p class="no-photo">تعذر تحميل الخريطة. جميع الأماكن ومسارات Google Maps متاحة في تفاصيل الأيام.</p>'}
function draw(days){if(!map)return;layers.clearLayers();let seen=new Set(),bounds=[];days.forEach(d=>{d.segments.forEach((s,i)=>{const r=window.ROUTES?.[`${d.n}-${i}`],actual=r?.coords;const xy=actual||s.points.map(k=>P[k].xy);L.polyline(xy,{color:colors[s.mode],weight:s.mode==='road'?4:3,opacity:.8,dashArray:actual?null:'6 7'}).addTo(layers).bindTooltip(s.mode==='road'?(actual?'طريق محسوب لسيارة عادية':'مسار تقريبي — التوجيه غير متاح'):s.mode==='ferry'?'عبّارة مركبات · خط تخطيطي':s.mode==='train'?'قطار ركاب · خط تخطيطي':s.mode==='boat'?'قارب ركاب · خط تخطيطي':'نقل / مشي');bounds.push(...xy)});d.stops.forEach(k=>{if(seen.has(k))return;seen.add(k);const c=CAMPS[k],p=P[k],night=DAYS.find(x=>x.camp===k);const ic=L.divIcon({className:'',html:`<div class="pin ${c?'sleep':'visit'}"><span>${c?night.n:'•'}</span></div>`,iconSize:[32,32],iconAnchor:[16,32]});L.marker(p.xy,{icon:ic}).addTo(layers).bindPopup(`<b>${esc(p.name)}</b><br>${c?'مخيم ليلة '+date(night)+'<br>':''}${link(maps(k),'Google Maps')}`);bounds.push(p.xy)})});if(bounds.length)map.fitBounds(bounds,{padding:[30,30]});map.invalidateSize()}
function selectDay(i){selected=i;$('routeSelect').value=i===null?'all':String(i);const d=i===null?null:DAYS[i];$('openSelected').disabled=i===null;$('mapStatus').textContent=window.L?(d?`اليوم ${d.n} · ${d.km} كم تقريبًا · ${d.drive}`:'الحلقة الكاملة · الطرق المحسوبة من OSRM بتاريخ 5 سبتمبر؛ النقل غير البري تخطيطي'):'الخريطة غير متاحة — استخدم روابط الأيام';$('selectedSummary').innerHTML=d?`<div><strong>${date(d)} · ${esc(d.title)}</strong><p>${esc(d.desc)}</p></div><button class="btn dark" id="summaryDetails">افتح جدول اليوم</button>`:`<div><strong>شمال غرب النرويج ← Sognefjord ← Hardanger ← أوسلو ← ستوكهولم</strong><p>الأرقام على العلامات الخضراء تشير إلى يوم المبيت؛ طريق بري مستمر مع عبّارات تربط المناطق.</p></div>`;if(d)$('summaryDetails').onclick=()=>openDay(i);draw(d?[d]:DAYS)}
$('routeSelect').onchange=e=>selectDay(e.target.value==='all'?null:Number(e.target.value));$('overview').onclick=()=>selectDay(null);$('openSelected').onclick=()=>{if(selected!==null)openDay(selected)};selectDay(null);
